### ISSUE TITLE
Update for Laravel 9

### ISSUE THREAD

**Issue by hetzner** [shaffe-fr/laravel-mail-log-channel#3]
`- shaffe/laravel-mail-log-channel v2.1.0 requires illuminate/queue ^5.6|^6.0|^7.0|^8.0`

Seems that this breaks the Laravel 8 -> 9 upgrade...

**Comment by shaffe-fr** [comment]
Hi, thanks for the issue, I'll look into it today!

**Comment by shaffe-fr** [comment]
Hi @hetzner, I pushed the  v2.2.0-beta tag. 
Composer update is working.
However as the underlying mailer of L9 changed, can you tell me if other changes are needed?
Thanks

**Comment by shaffe-fr** [comment]
The package still works with new mailer system. A new v2.2.0 release is out.
