### ISSUE TITLE
Segfault when used as part of stack driver

### ISSUE THREAD

**Issue by jbeales** [shaffe-fr/laravel-mail-log-channel#4]
I'm having a problem where I get a segmentation fault when the mail channel is part of the stack driver in Laravel 9. This didn't happen in Laravel 8.

My default log channel is the stack driver with this config:
```
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily' , 'mail'],
            'ignore_exceptions' => false,
        ],
```
This is the config for my mail driver:
```
        'mail' => [
            'driver' => 'mail',
            'level'  => 'error',
            // Specify who to mail the log to
            'to' => [
                [
                    'address' => 'jxxx@xxxxxxmycompanyxxx.com',
                    'name' => 'John B',
                ],
            ],
        ],
```
Then I run this artisan command, or trigger an error, and I get a segmentation fault:
```
Artisan::command('mail-log', function() {
    Log::error('Test Mail Error.');
});
```

I'm stepping through it in Xdebug and something within `$this->mailer = app()->make('mailer');` on line 40 of `src/Monolog/Handlers/MailableHandler.php` seems to get into a recursive loop. I suspect something isn't resolving so we keep trying to build a new stack log driver, which builds a new mail log driver, which does't resolve making the mailer, so we build a new stack log driver, which builds a new mail log driver.... etc. I'm not sure if there's an error being thrown making the mail log channel, or it simply is getting passed a "null" somewhere, so defaults to the default log channel - which is the stack channel.

**Comment by jbeales** [comment]
I tried a couple of other things to help isolate why the problem is happening:

1.  Setting my default log channel to 'daily', then sending the error directly to the stack log channel, and there was no error. 2. Setting my default log channel to 'mail', then sending the error message directly to the stack log channel, and I got a segfault.

Having the mail channel as part of the default logger seems to be the problem.

**Comment by jbeales** [comment]
SOLVED!

I'm having the problem on my dev machine, where I'm using the 'log' mailer, but with no `mail.log_channel` config set. Because I had no log channel, it looked for the default, which was stack, which contains mail, and we went down the recursive rabbit hole.

Setting MAIL_LOG_CHANNEL in my local .env to 'daily' fixed the problem for me.

**Comment by shaffe-fr** [comment]
Hi, great you found a fix!
You can maybe create a specific log stack for you dev machine?

**Comment by jbeales** [comment]
Yeah, just setting the MAIL_LOG_CHANNEL in my dev machine's .env file solved it. That way I don't need specific code for dev. Once it wasn't trying to direct the mail messages into a log, and part of that log included sending a mail message, we got out of the loop.

Using Mailtrap or something would also work.
