### ISSUE TITLE
Anyway of excluding a certain user?

### ISSUE THREAD

**Issue by u01jmg3** [shaffe-fr/laravel-mail-log-channel#6]
How do I exclude a certain user so that the mail logging doesn't happen if I'm logged into the application as myself? I only need to be emailed and notified if someone other than myself has triggered an error.

Thanks

**Comment by shaffe-fr** [comment]
Hi, 
you can try to use the shouldReport method of the exceptions Handler and test for the connected user.

**Comment by u01jmg3** [comment]
Looks like `shouldReport()` has been renamed to [`reportable()`](https://github.com/laravel/laravel/blob/10.x/app/Exceptions/Handler.php#L26) and is now placed within the `register()` method.

Although I can override my stack channel using `config(['logging.channels.stack.channels' => 'daily']);` (to turn off the `mail` logger), I am unable to get the current user as the session has not yet started and `auth()->user()` just returns `null`.

**Comment by shaffe-fr** [comment]
Hi,
I did the following in `\App\Exceptions\Handler` and it works.

```php
class Handler extends ExceptionHandler
{
   //...
    public function register(): void
    {
        $this->reportable(function (\Throwable $e) {
            return auth()->id() !== 1;
        });
    }
    //...
}
```

**Comment by u01jmg3** [comment]
Thanks but unfortunately that doesn't work for me as `auth()->id()` is `null`. I also want to only omit sending an email if I'm logged in but leave logging the error to file as is. (i.e. `config(['logging.channels.stack.channels' => 'daily'])`)

What middleware do you have defined?

```php
class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        // \App\Http\Middleware\TrustProxies::class,
        \Illuminate\Http\Middleware\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \App\Http\Middleware\ForceHttps::class,
            \App\Http\Middleware\ForceWww::class,
            \App\Http\Middleware\SecurityHeaders::class,
            \App\Http\Middleware\SeoRedirects::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

**Comment by shaffe-fr** [comment]
Unless the exceptions occurs on a route without the auth middleware, I dont think it's something about middleware. Are you using a custom guard?
I understand what you want, I'll think about something!
I'll come back to you asap!

**Comment by shaffe-fr** [comment]
Hi @u01jmg3,
You can create a middleware that swaps the logging channel for you user.
Make sure the middleware is after the `StartSession` middleware.

The middleware can look like this:

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ChangeLoggingChannelForRootUserMiddleware
{
    public function __invoke(Request $request, $next)
    {
        if ($request->user()?->getKey() == 1) {
            Log::setDefaultDriver('daily');
        }

        return $next($request);
    }
}

```

**Comment by u01jmg3** [comment]
Thanks for providing this code - the middleware successfully grabs the user from the session. The only problem is that `Log::setDefaultDriver('daily');` has no effect as I'm still getting emails (although I've checked that the code does run).

Presumably, I'm too high up in the execution stack but I have to place your middleware after `StartSession`. Any ideas?

**Comment by shaffe-fr** [comment]
Hi, 
obviously the error must be thrown after the middleware is callee. What channel do you want to use for you?

**Comment by u01jmg3** [comment]
What about if it's a compilation error rather than manually throwing one?

**Comment by shaffe-fr** [comment]
It should work as well for native errors especially if you still receive the error mail.

**Comment by u01jmg3** [comment]
Yes, email works. But running `Log::setDefaultDriver('daily')` in the middleware doesn't turn the emails off as it is supposed to when I'm logged in as the root user (`id=1`) and a compilation error is caused.

**Comment by shaffe-fr** [comment]
What happens if you switch the default channel without the if statement? Does it still send emails?

**Comment by u01jmg3** [comment]
Yep, emails still come through.

The only way it works is by placing a middleware containing just `Log::setDefaultDriver('daily')` in [`Kernel.php::$middleware`](https://github.com/laravel/laravel/blob/10.x/app/Http/Kernel.php#L16) rather than [`Kernel.php::$middlewareGroups['web']`](https://github.com/laravel/laravel/blob/10.x/app/Http/Kernel.php#L31) after `StartSession`. But then you have no access to the session. Catch 22

**Comment by shaffe-fr** [comment]
Is the exception thrown in a middleware before the controller? Looks like its thrown too soon

**Comment by u01jmg3** [comment]
For testing purposes, I just omitted a semicolon in one of my controllers to generate a Whoops page. I had hoped your new middleware would prevent being emailed.

**Comment by shaffe-fr** [comment]
Can you try to throw an exception from a controller?

**Comment by shaffe-fr** [comment]
I didn't try it, but you can also add a listener on the Authenticated event to swap the default driver.

**Comment by u01jmg3** [comment]
Calling `throw new \ErrorException('Error found');` in my controller (rather than omitting a `;`) and the middleware works as intended. 👍🏻

Will try out your listener idea

**Comment by shaffe-fr** [comment]
Great!
I think the listener way should be more bullet proof.
